# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c529c8cac45c9d10e2b7841622a46ddad0926a90ded1f8c1016d248d11f993f441a3d161718142924b1fe020c5e9900205a91e6c97413199d4254da23c916422

test:
  secret_key_base: f8b6cdf8fe5a0361163978eb61a412e8fa83c1c02333c7d911a009820e76391a6f11830b2145dd19cd03626cb0267aaefd6d27d17f293aa878add03bb5bd8184

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
